BEGIN;

CREATE TABLE IF NOT EXISTS pipeline (id SERIAL PRIMARY KEY, last_update TIMESTAMP WITH TIME ZONE DEFAULT NOW());
CREATE TABLE IF NOT EXISTS pipeline_step (id SERIAL PRIMARY KEY, step_number INT NOT NULL, parent_id int, pipeline_id INT NOT NULL, target_namespace TEXT NOT NULL, auto_deploy BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS deployment (id SERIAL PRIMARY KEY, chart TEXT NOT NULL, repository_url TEXT NOT NULL, pipeline_id INT, creation_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(), last_update TIMESTAMP WITH TIME ZONE DEFAULT NOW());
CREATE TABLE IF NOT EXISTS release (id SERIAL PRIMARY KEY, deployment_id INT NOT NULL, timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(), namespace TEXT NOT NULL, image TEXT NOT NULL, tag TEXT NOT NULL);

CREATE INDEX ON pipeline_step (pipeline_id);
CREATE INDEX ON pipeline_step (id, parent_id);
ALTER TABLE pipeline_step ADD CONSTRAINT FK_PIPELINE_STEP_PIPELINE_ID FOREIGN KEY (pipeline_id) REFERENCES pipeline (id);
ALTER TABLE pipeline_step ADD CONSTRAINT FK_PIPELINE_STEP_PARENT_ID FOREIGN KEY (parent_id) REFERENCES pipeline_step (id);
ALTER TABLE pipeline_step ADD CONSTRAINT PIPELINE_STEP_UNIQUE_STEP_NUMBER_PIPELINE_ID UNIQUE (step_number, pipeline_id);
ALTER TABLE deployment ADD CONSTRAINT DEPLOYMENT_UNIQUE_CHART UNIQUE (chart);
ALTER TABLE deployment ADD CONSTRAINT FK_DEPLOYMENT_PIPELINE_ID FOREIGN KEY (pipeline_id) REFERENCES pipeline (id);
CREATE INDEX on release (deployment_id);
ALTER TABLE release ADD CONSTRAINT FK_RELEASE_DEPLOYMENT_ID FOREIGN KEY (deployment_id) REFERENCES deployment (id);

COMMIT;
